ipv6: false
mode: rule
log-level: info
allow-lan: true
geodata-mode: true
geodata-loader: memconservative
external-controller: 127.0.0.1:9090
external-ui: dashboard
unified-delay: true
global-client-fingerprint: firefox

profile:
  store-selected: true

geox-url:
    geoip: https://ghproxy.com/https://github.com/malikshi/v2ray-rules-dat/releases/latest/download/geoip.dat
    geosite: https://ghproxy.com/https://github.com/malikshi/v2ray-rules-dat/releases/latest/download/geosite.dat

dns:
  enable: true
  ipv6: true
  nameserver:
    - 1.0.0.1
    - 112.215.198.248
    - 112.215.198.254
    - 112.215.203.248
    - 202.152.254.245
    - 202.152.254.246
  fallback:
    - 1.0.0.1
    - 112.215.198.248
    - 112.215.198.254
    - 112.215.203.248
    - 202.152.254.245
    - 202.152.254.246
  default-nameserver:
    - 1.0.0.1
    - 112.215.198.248
    - 112.215.198.254
    - 112.215.203.248
    - 202.152.254.245
    - 202.152.254.246

proxy-providers:
  Akun-VIP:
    type: file
    path: "./Akun-VIP.yaml"
    health-check:
      enable: true
      url: 'http://cp.cloudflare.com'
      interval: 60
  Bitz-Black:
    type: file
    path: "./Bitz-Black.yaml"
    health-check:
      enable: true
      url: 'http://cp.cloudflare.com'
      interval: 60
  Mas-Fen:
    type: file
    path: "./Mas-Fen.yaml"
    health-check:
      enable: true
      url: 'http://cp.cloudflare.com'
      interval: 60

proxy-groups:
  - name: ADS
    type: select
    health-check:
      enable: true
      url: 'http://cp.cloudflare.com'
      interval: 60
    proxies:
      - DIRECT
      - REJECT
      - AKUN VIP
    default:
      use: REJECT
  - name: AKUN VIP
    type: select
    health-check:
      enable: true
      url: 'http://cp.cloudflare.com'
      interval: 60
    proxies:
      - DIRECT
      - REJECT
      - Bitz Black
      - Mas Fen
    use:
      - Akun-VIP
  - name: Bitz Black
    type: select
    health-check:
      enable: true
      url: 'http://cp.cloudflare.com'
      interval: 60
    proxies:
      - DIRECT
      - REJECT
    use: 
      - Bitz-Black
  - name: Mas Fen
    type: select
    health-check:
      enable: true
      url: 'http://cp.cloudflare.com'
      interval: 60
    proxies:
      - DIRECT
      - REJECT
    use: 
      - Mas-Fen
  - name: WOWS
    type: select
    health-check:
      enable: true
      url: 'http://cp.cloudflare.com'
      interval: 60
    proxies:
      - DIRECT
    use:
      - Akun-VIP

rules:
  - RULE-SET,WOWS,WOWS
  - RULE-SET,ABP-Domain,ADS
  - RULE-SET,ABP-Suffix,ADS
  - RULE-SET,ABP,ADS
  - RULE-SET,OISD,ADS
  - MATCH,AKUN VIP

rule-providers:
  FB-YT:
    type: file
    behavior: classical
    path: "./FB-YT.yaml"
  WOWS:
    type: file
    behavior: classical
    path: "./WOWS.yaml"
  ABP-Domain:
    type: file
    behavior: classical
    path: "./ABP-Domain.yaml"
  ABP-Suffix:
    type: file
    behavior: classical
    path: "./ABP-Suffix.yaml"
  ABP:
    type: file
    behavior: classical
    path: "./ABP.yaml"
  OISD:
    type: file
    behavior: classical
    path: "./OISD.yaml"
